changed cd workflow to check secrets

diff --git a/.github/workflows/reusable-continuous-delivery.yml b/.github/workflows/reusable-continuous-delivery.yml
--- a/.github/workflows/reusable-continuous-delivery.yml
+++ b/.github/workflows/reusable-continuous-delivery.yml
@@ -42,10 +42,13 @@ on:
         default: false
         type: boolean
       registry:
-        description: The registry to publish to, either `npm` or `github`
+        description: The registry to publish to, either `npm`, `github` or `both`
         required: true
         type: string
     secrets:
+      GH_AUTH_TOKEN:
+        description: The token to authenticate with the Github registry
+        required: false
       NPM_AUTH_TOKEN:
         description: The token to authenticate with the NPM registry
         required: false
@@ -71,6 +74,25 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           submodules: ${{ inputs.with-submodules }}
 
+      - name: Check Required Secrets
+        env:
+          REGISTRY: ${{ inputs.registry }}
+          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
+          GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
+        run: |
+          if [[ "$REGISTRY" == "npm" || "$REGISTRY" == "both" ]]; then
+            if [[ -z "$NPM_AUTH_TOKEN" ]]; then
+              echo "Error: NPM_AUTH_TOKEN is required when publishing to npm registry."
+              exit 1
+            fi
+          fi
+          if [[ "$REGISTRY" == "github" || "$REGISTRY" == "both" ]]; then
+            if [[ -z "$GH_AUTH_TOKEN" ]]; then
+              echo "Error: GH_AUTH_TOKEN is required when publishing to GitHub registry."
+              exit 1
+            fi
+          fi
+
       - name: Install Dependencies
         uses: zendrex/zendrex/.github/actions/install-bun-dependencies@main
         with:
@@ -80,19 +102,6 @@ jobs:
         if: ${{ inputs.build }}
         run: bun build
 
-      - name: Configure Package Registries
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
-          REGISTRY: ${{ inputs.registry }}
-        run: |
-          if [ "${REGISTRY}" = "npm" ]; then
-            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
-          fi
-          if [ "${REGISTRY}" = "github" ]; then
-            echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
-          fi
-
       - name: Bump Version
         working-directory: ${{ inputs.working-directory }}
         env:
@@ -101,17 +110,23 @@ jobs:
           bun run bump --preid "${TAG}.$(git rev-parse --short HEAD)" --skip-changelog
 
       - name: Publish to NPM Registry
-        if: ${{ inputs.registry == 'npm' }}
+        if: ${{ inputs.registry == 'npm' || inputs.registry == 'both' }}
         working-directory: ${{ inputs.working-directory }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
         run: |
+          echo "//registry.npmjs.org/:_authToken=${AUTH_TOKEN}" > ~/.npmrc
+
           bun x npm publish --tag ${TAG} --registry https://registry.npmjs.org/
 
       - name: Publish to GitHub Registry
-        if: ${{ inputs.registry == 'github' }}
+        if: ${{ inputs.registry == 'github' || inputs.registry == 'both' }}
         working-directory: ${{ inputs.working-directory }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
         run: |
+          echo "//npm.pkg.github.com/:_authToken=${AUTH_TOKEN}" > ~/.npmrc
+
           bun x npm publish --tag ${TAG} --registry https://npm.pkg.github.com/${{ github.repository_owner }}
